cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/wan/Desktop/High-Precision-Congestion-Control-master/simulation/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/wan/Desktop/High-Precision-Congestion-Control-master/simulation/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 140358990388496: cxxprogram test.cpp.1.o -> testprog}\n[\'g++-5\', \'-Wl,-Bsymbolic-functions\', \'-Wl,-z,relro\', \'test.cpp.1.o\', \'-o\', \'/home/wan/Desktop/High-Precision-Congestion-Control-master/simulation/build/.conf_check_bb4ab0a2da6fec0567ee396296163b23/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/libs\', \'-lpython2.7m\']\n'
